- README.md
I made the change on a branch. This way I will see the change, but it won't be merged into master outside of the PR process.
> Added my name to README.

- .github/pull_request_template.md
This PR adds a pull request template that will populate every PR description with the template seen on this PR. 
- https://eulogy-quest.youtrack.cloud/issue/EUL_51
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/ISSUE_NUMBER
> [EUL-51]: Add pull request template to repo 

- README.md
The next person to make a change should delete the bracketed yourName and enter their own name followed by a comma.
_<What changed? Why?>_
- https://eulogy-quest.youtrack.cloud/issue/EUL_ISSUE_NUMBER
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/ISSUE_NUMBER
> Adding demo change to README.md. Added "yourName, " to README.md

- README.md
Adds Richard Vargason to readme file, proves out part of github workflow 
- https://eulogy-quest.youtrack.cloud/issue/EUL_54
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/ISSUE_NUMBER
> [EUL-54]: Update readme with Richard Vargason

- README.md
- docker-compose.yml
Added my name to the Readme file. This served as an initial exercise in practicing our github workflow. 
- https://eulogy-quest.youtrack.cloud/issue/EUL-55
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/5
> (EUL-55): Added John to Readme

- README.md
Added my name to the README file as the first part of the practicing our github workflow.
- https://eulogy-quest.youtrack.cloud/issue/EUL-56
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/11
> [EUL-56] Solidify GitHub workflow by adding name to Readme/editing NPC (Jayson Kirchand-Patel)

- README.md
Added my name to readme.md
- https://eulogy-quest.youtrack.cloud/issue/EUL-58
- N/A
> [EUL-58] Solidify GitHub workflow by adding name to Readme (Hardy Fenam)

- server/quests/tutorialb/Vahlara.pl
Added my name to the NPC Vahlara, realized these changes in my local server and pushed these changes as an exercise in solidifying our Github workflow. 
- https://eulogy-quest.youtrack.cloud/issue/EUL-55 
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/15
> [EUL-55] Made changes to NPC "Vahlara"

- server/quests/tutorialb/Vahlara.pl
Added my name to NPC "Vahlara"'s dialogue for the second part of practicing our github workflow. 
Closes #11 
- https://eulogy-quest.youtrack.cloud/issue/EUL-56
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/11
> [EUL-56] Solidify GitHub workflow by editing NPC (Jayson Kirchand-Patel)

- server/quests/tutorialb/Vahlara.pl
I edited the Vahlara NPC's dialogue.
- https://eulogy-quest.youtrack.cloud/issue/EUL-58
- N/A
> [EUL-58] Solidify GitHub workflow by editing NPC (Hardy Fenam)

- README.md
Added "Parham" to README
- https://eulogy-quest.youtrack.cloud/issue/EUL-59
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/24
> Added Parham Pahlavan to ReadMe

- README.md
Added Name to README.md
- https://eulogy-quest.youtrack.cloud/issue/EUL-61
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/25
> EUL-61 Solidify GitHub workflow by adding name to Readme (Adam Hamou)

- server/quests/tutorialb/Vahlara.pl
Added Parham Pahlavan to the Vahlara.pl file.
- https://eulogy-quest.youtrack.cloud/issue/EUL-59
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/27
> Added Parham Pahlavan to NPC

- server/quests/tutorialb/Vahlara.pl
Added my name to NPC output
- https://eulogy-quest.youtrack.cloud/issue/EUL-61
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/25
> EUL-61 Solidify GitHub workflow by adding name to editing NPC (Adam Hamou)

- README.md
Added my name (Michael Soffer) to the README.md file, solidifying our team GitHub workflow
- https://eulogy-quest.youtrack.cloud/issue/EUL-60
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/46
> [EUL-60] Closes #46 - Add Michael Soffer to README

- server/quests/tutorialb/Vahlara.pl
Closes issue #39, and shows a working Github workflow of local development, then pushing to rest of team. 
- https://eulogy-quest.youtrack.cloud/issue/EUL-54
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/39
> [EUL-54] Added Richard to Vahlara dialogue

- server/quests/tutorialb/Vahlara.pl
Added my name to NPC Vahlaras' dialogue to solidify our team's GitHub workflow by editing a part of the code. 
- https://eulogy-quest.youtrack.cloud/issue/EUL-60
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/53
> Added Michael to Vahlara NPC. Closes #53

- website/client/src/comp/NavBar.css
- website/client/src/comp/NavBar.js
- website/client/src/comp/about.js
Added an about us section. Right now it doesn't have much text, but the functionality is there.
- https://eulogy-quest.youtrack.cloud/issue/EUL-101
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/36
> Website about

- website/client/src/comp/NavBar.css
- website/client/src/comp/NavBar.js
Added navigation functionality to the website. Closes #35.
- https://eulogy-quest.youtrack.cloud/issue/EUL-100
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/35
> added navbar functionality

- website/client/package-lock.json
- website/client/package.json
- website/client/src/comp/prompt.js
Added the input prompt and handling for input, aka added UI css and html, centered it, and gave a response weather a message was sucessful sent or failed closes #33 
- https://eulogy-quest.youtrack.cloud/issue/EUL-95
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/33
> EUL-95 prompt input user interface

- .github/workflows/lua-linter.yml
Created a Lua linter GitHub action for our GitHub workflow CI/CD pipeline. This tool automates quality control for .lua files, and will analyze any .lua code uploaded in a PR. This will ultimately help our team write cleaner, bug-free Lua code for our project. 
- https://eulogy-quest.youtrack.cloud/issue/EUL-105
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/55
> [EUL-105] Added lua linter for .lua files to the github workflow. Closes #55

- README.md
Fixed a name overwrite error in the README file where my name was overwritten by another PR. 
- https://eulogy-quest.youtrack.cloud/issue/EUL-107
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/62
> Fix README overwrite error. Closes #62

- .github/ISSUE_TEMPLATE/feature_request.md
Added a template for writing feature requests
- https://eulogy-quest.youtrack.cloud/issue/EUL-92
-
> Added an issue template for writing feature requests

- README.md
I changed the REAME.md as per the professor's recommendation to include:
- Project Overview
- Setup & Installation
- Technology Stack
- Deployment Instructions
I also included our logo and links to our repo and to our documentation/guides.
- [EUL-108](https://eulogy-quest.youtrack.cloud/issue/EUL-108) Update README.md per johnxu211's suggestion
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/64
Closes #64
> EUL-108 Update README.md per johnxu211's suggestion

- .gitignore
- website/README.md
- website/server/server.py
- Integrated python-dotenv to securely load the OpenAI API key from a .env file
- Updated server.py to use the API key from environment variables
- Added python-dotenv to dependencies list for the website
- Added setup instructions for .env usage in website/server/README.md
- Updated .gitignore to ignore virtual environment setups
Support for OpenAI API is now implemented for use on the website, this is an important step for when users will want to generate quests, the website will directly communicate with the OpenAI API and the LLM will eventually output the quest for the user. 
- https://eulogy-quest.youtrack.cloud/issue/EUL-122
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/76
> Added OpenAI support via environment variable and updated dependencies

- .github/workflows/ken/login.ahk
- Eulogy-Quest/eulogy-docs/local-game-server-validation-scripts/login.ahk
The game isn't started via the script when called in the GitHub Action (although the script works --and has this whole time-- via manual launching). So, I'm adding logging to the .ahk script to pinpoint the issue.
- [EUL-117](https://eulogy-quest.youtrack.cloud/issue/EUL-117) GitHub Action Validate-EQEmu (Bugfix)
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/72
> Added logfile for login.ahk actions for debugging

- .github/workflows/ken/login.ahk
The ahk script is not creating the log file. Trying now to create the ahk logfile on the Desktop; permission issue?
- [EUL-117](https://eulogy-quest.youtrack.cloud/issue/EUL-117) GitHub Action Validate-EQEmu (Bugfix)
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/72
> chaning ahk logfile location to Desktop. Still debugging.

- .github/workflows/ken/login.ahk
Bugfix ongoing. Adding test to see if the ahk script login.ahk is called --at all.
- [EUL-117](https://eulogy-quest.youtrack.cloud/issue/EUL-117) GitHub Action Validate-EQEmu (Bugfix)
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/72
> Sanity-check. Is the login.ahk script called --at all?

- .gitignore
edited .gitignore file to ignore cache, config, and environment Python files. 
files included were based on Githubs .gitignore template for Python.
(see here: https://github.com/github/gitignore/blob/main/Python.gitignore)
Importantly, I included:
- Flask related files (instance/, .webassets-cache)
- Virtual environment directories (.env, .venv, env/, venv/)
- Python cache files (\_\_pycache__/, .pyc, py.class)
- https://eulogy-quest.youtrack.cloud/issue/EUL-118
Resolves Issue: #74
> [EUL-118] edited .gitignore to ignore cache, config, and environment Python files

- website/server/server.py
Implemented a functional GPT backend for the famous person route of the website. When the user types in a famous persons name the backend will communicate to OpenAI via API key and generate a quest using ChatGPT model 3.5 turbo. Output is a JSON file. 
- https://eulogy-quest.youtrack.cloud/issue/EUL-115
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/90
> Implemented an operational GPT backend that generates a quest for a famous person. Closes #90.

- .github/ISSUE_TEMPLATE/Bugfix Issue
Create a template to the issue tab for any bug problem fix to be recorded.
- https://eulogy-quest.youtrack.cloud/issue/EUL-91
https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/93
> Create Bugfix Issue Template

- Eulogy-Quest/triggers/README.txt
- Eulogy-Quest/triggers/aws-quest-gen-script.py
This provides a 'one-click' script to create a Eulogy-Quest on our AWS server.
Use: ./aws-quest-gen-script.py "Firstname Lastname"
This should help with getting the Eulogy-Quest project finished.
N/A
- https://eulogy-quest.youtrack.cloud/issue/EUL-142 (Closes this youtrack ticket)
> Script which immediately creates the quest on the AWS server

- website/client/src/comp/Honoredone.js
- website/server/before_ai.json
Added a response to the submit button of the Honored One section so that it matches the one in the Famous Person section.
- https://eulogy-quest.youtrack.cloud/issue/EUL-149
- https://github.com/UNLV-CS472-672/2025-S-GROUP4-EulogyQuest/issues/132
- Closes #132
> Add response to the submit button of the Honored One Section

- Eulogy-Quest/GPT/create-quest.py
- Eulogy-Quest/GPT/prompts/Ghost-dialog-Christopher_Reeve.txt
- Eulogy-Quest/GPT/prompts/old_Ghost-prompt/Ghost-prompt.txt
- Eulogy-Quest/GPT/prompts/prompt-tester.py
See prompt-tester.py and the resulting file for the current stage of prompt improvement. This prompt is geared towards the text for the honored_target/ghost NPC, and I'll iterate on this. The upload is so that others (John/Michael/etc.) can use this as a starting point for the other NPCs and for the item generation/placement. New prompt scripts can be created using this ghost text creation script as a guide/template.
This script refines the files used in the purple section in the UML diagram below, leading to files output to the 'intermediate files' section below that.
Related youtrack tickets:
- [EUL-136](https://eulogy-quest.youtrack.cloud/issue/EUL-136) Improve quest dialog quality (not click-text, yet)
- [EUL-140](https://eulogy-quest.youtrack.cloud/issue/EUL-140) Item descriptors and …
> mid-point PR of the quest-text improvement (for the ghost npc). 

- website/server/requirments.txt
Added requirments file for easier installation on serverend
None
None
> added requirments folder for eaiser installation on serverside

- Eulogy-Quest/GPT/updateNPCs.py
files changed: updateNPCs.py
updateNPCs.py script inserts npc and item SQL into the MariaDB docker container, however there is no logging to show when it executes these insertions successfully or unsuccessfully.
These changes adds logs (w/ 'logging' library) to output.
I have included in the logs:
- the file name ('[updateNPCs.py]') in the lines output to console to identify the execution file.
- the item/NPC name inserted
- the item/NPC id
The goal of this PR is to better pinpoint where problems occur within the pipeline.
example of successful run from running from master script:
```python3 create-quest.py Lebron\ James```
example of logging unsuccessful run (MariaDB container not running):
it logs the error and exits immediately. (as expected)
Screenshot in-game to verify the script …
> [EUL 150] updated logging for updateNPCs.py - Hardy Fenam
